server:
  port: 8090
logging:
  level:
    org.springframework.cloud.config.server.environment: warn

spring:
  config:
    import:
      - optional:configtree:/etc/run/
      - optional:classpath:other.properties
